environment:
    matrix:
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: 3.7
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: 3.6

install:
    - "SET ORIGPATH=%PATH%"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda update -q conda
    - conda install conda-build anaconda-client
    - conda info -a
    - 'SET PYTHONWARNINGS=ignore:mode:DeprecationWarning:docutils.io:245'
    - "IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (SET GIT_BRANCH=%APPVEYOR_REPO_BRANCH%)"

build: off

test_script:
    - setlocal
    - set CONDA_REPO_TOKEN=
    - conda build conda-recipe --python %PYTHON_VERSION%
    - endlocal

deploy_script:
    - cmd: "python ci\\deploy_anaconda.py"
