{% set name = "psy-strat" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ CONDA_PY }}_{{ environ.get('GIT_BUILD_STR', '') }}{% if environ.get('GIT_BRANCH') %}_{{ environ.get('GIT_BRANCH').replace('-', '') }}{% endif %}
  script: python -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py == 27]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - psy-simple >=1.2.0
    - psyplot >=1.2.0
    - numpy >=1.14  # [win]
    - xarray !=0.13.0

test:
  requires:
    - pytest
    - codecov
    - pytest-cov
    - psyplot-gui
    - pyqt>5.7   # [osx]
  source_files:
    - tests
  imports:
    - psy_strat
  commands:
    - pytest -v --cov=psy_strat
    - codecov


about:
  home: https://github.com/Chilipp/psy-strat
  license: GPLv2
  license_family: GPL2
  license_file: LICENSE
  summary: 'Python package for digitizing pollen diagrams'

  description: |
    Python package for creating stratigraphic diagrams
  doc_url: http://psy-strat.readthedocs.io/
  dev_url: https://github.com/Chilipp/psy-strat
